from vehicle import DECK_SIZE
PROPULSIONS = {
    'sails': {
        'name': 'Sails',
        'cost': 25,
        'power': 1,
        'weight': 0.2,
        'hp': 20,
        'hardness': 0,
        'external': True,
        'required_crew': 1.0 / DECK_SIZE,
        'crew_type': 'Sailors',
    },
    'sails_silk': {
        'name': 'Sails, silk',
        'cost': 225,
        'power': 2,
        'weight': 0.1,
        'hp': 30,
        'hardness': 0,
        'external': True,
        'required_crew': 1.0 / DECK_SIZE,
        'crew_type': 'Sailors',
    },
    'oars': {
        'name': 'Oars',
        'cost': 15,
        'power': 2,
        'weight': 0.1,
        'hp': 20,
        'external': False,
        'required_crew': 4,
        'crew_type': 'Sailors',
    },
    'oars_air': {
        'name': 'Oars, air',
        'cost': 135,
        'power': 2,
        'weight': 0.2,
        'hp': 20,
        'external': False,
        'required_crew': 4,
        'crew_type': 'Sailors',
    },
    'manual': {
        'name': 'Manual',
        'cost': 25,
        'power': 2,
        'weight': 1,
        'hp': 20,
        'external': False,
        'required_crew': 2,
        'crew_type': 'Sailors',
    },
    'steam_inf': {
        'name': 'Steam, inferior',
        'cost': 100,
        'power': 6,
        'weight': 4,
        'hp': 40,
        'external': False,
        'required_crew': 1,
        'crew_type': 'Engineer',
    },
    'steam': {
        'name': 'Steam',
        'cost': 175,
        'power': 9,
        'weight': 5,
        'hp': 50,
        'external': False,
        'required_crew': 1,
        'crew_type': 'Engineer',
    },
    'steam_sup': {
        'name': 'Steam, superior',
        'cost': 250,
        'power': 12,
        'weight': 6,
        'hp': 60,
        'external': False,
        'required_crew': 1,
        'crew_type': 'Engineer',
    },
    'alchemical_inf': {
        'name': 'Alchemical, inferior',
        'cost': 300,
        'power': 9,
        'weight': 3,
        'hp': 60,
        'external': False,
        'required_crew': 1,
        'crew_type': 'Engineer',
    },
    'alchemical': {
        'name': 'Alchemical',
        'cost': 750,
        'power': 20,
        'weight': 5,
        'hp': 100,
        'external': False,
        'required_crew': 1,
        'crew_type': 'Engineer',
    },
    'alchemical_sup': {
        'name': 'Alchemical',
        'cost': 500,
        'power': 12,
        'weight': 4,
        'hp': 80,
        'external': False,
        'required_crew': 1,
        'crew_type': 'Engineer',
    },
    'elemental_air': {
        'name': 'Elemental, Air',
        'cost': 1000,
        'power': 20,
        'weight': 2,
        'hp': 30,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
    'elemental_earth': {
        'name': 'Elemental, Earth',
        'cost': 1000,
        'power': 20,
        'weight': 2,
        'hp': 140,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
    'elemental_water': {
        'name': 'Elemental, Water',
        'cost': 1000,
        'power': 15,
        'weight': 2,
        'hp': 80,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
    'elemental_fire': {
        'name': 'Elemental, fire',
        'cost': 1000,
        'power': 25,
        'weight': 2,
        'hp': 80,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
    'vampiric': {
        'name': 'Vampiric',
        'cost': 2500,
        'power': 50,
        'weight': 2,
        'hp': 100,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
    'Enchantment': {
        'name': 'Enchantment',
        'cost': 5000,
        'power': 10,
        'weight': 0,
        'hp': 0,
        'external': False,
        'required_crew': 0,
        'crew_type': 'Engineer',
    },
    'necrotic': {
        'name': 'Necrotic',
        'cost': 5000,
        'power': 75,
        'weight': 2,
        'hp': 100,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
    'spell': {
        'name': 'Spell',
        'cost': 7500,
        'power': 75,
        'weight': 1,
        'hp': 100,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
    'Shadow': {
        'name': 'Shadow',
        'cost': 10000,
        'power': 100,
        'weight': 1,
        'hp': 120,
        'external': False,
        'required_crew': 1 / DECK_SIZE / 5,
        'crew_type': 'Engineer',
    },
}
